kubansite/kubansite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from pages.views import category, contacts, index, katalog, product, privacy, agreement

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('feedback/', contacts, name='contacts'),
    path('catalog/', katalog, name='katalog'),
    path('category/<slug:slug>/', category, name='category'),
    path('product/<int:product_id>/', product, name='product'),
    path('privacy/', privacy, name='privacy'),
    path('agreement/', agreement, name='agreement')
]
handler404 = 'pages.views.page_not_found'
handler500 = 'pages.views.e_handler500'
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

kubansite/pages/forms.py
from django import forms
from .models import WeightCategory


class ContactForm(forms.Form):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder':
                   '*Ваше имя',
                     'class': 'popup__input form__input'}))  # Имя
    phone_number = forms.RegexField(
        regex='^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$',
        widget=forms.TextInput(attrs={'placeholder': '* +7-999-999-99-99',
                                      'class': 'popup__input form__input',
                                      'type': 'tel',
                                      'pattern': '^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7,10}$'}))  # Номер телефона
    e_mail = forms.EmailField(widget=forms.EmailInput(
        attrs={'placeholder': '*Ваш e-mail',
               'class': 'popup__input form__input',
               'pattern': "[a-zA-Z0-9_\-]+@[a-zA-Z]+\.[a-z]+"}),
                max_length=50)  # Электронная почта
    region = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Ваш регион (страна, город, район, населенный пункт)',
                   'class': 'form__input'}), max_length=100, required=False)  # Регион
    sales_channel = forms.ChoiceField(
        choices=(('Retail', 'Retail'),
                 ('Дистрибуция', 'Дистрибуция'),
                 ('Физ.лицо', 'Физ.лицо')),
        widget=forms.Select(attrs={'class': 'popup__select'}))
    nalog = forms.ChoiceField(
        choices=(('-', '-'), ('НДС', 'НДС'), ('Без НДС', 'Без НДС')),
        widget=forms.Select(attrs={'class': 'popup__select'}))   # Вид налога
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={'placeholder': 'Сообщение',
                   'class': 'popup__input_type_text form__input'}), max_length=200, required=False)
    rules = forms.BooleanField(
        label='Я принимаю условия пользовательского соглашения',
        widget=forms.CheckboxInput(
            attrs={'class':
                   'popup__input form__input form__input_el_extra_options'}))

class WeightForm(forms.ModelForm):
    title = forms.ModelChoiceField(empty_label=None, queryset=WeightCategory.objects.all(),
    widget=forms.widgets.Select(
      attrs={'class': 'filter__input'}))
    class Meta:
        model =  WeightCategory
        fields = ['title']

kubansite/pages/templates/pages/agreement.html
{% extends "base.html" %}
{% load static %}
{% block title %}Пользовательское соглашение{% endblock title %}
{% block keywords %}кондитерские изделия, оптом, конфеты, печенье, торты{% endblock keywords %}
{% block description %}На данной странице приведено Пользовательское соглашение, с которым могут ознакомиться пользователи{% endblock description %}
{% block content %}
<main class="content">
  <section class="agreement">
    <h1 class="section-title agreement__title">Пользовательское Соглашение</h1>
    <p class="agreement__text">Настоящее Пользовательское Соглашение (Далее Соглашение) регулирует отношения между ИП Цыганкова Ирина Владимировна (далее Кубанская кормилица или Администрация) с одной стороны и пользователем сайта с другой.
      Сайт Кубанская кормилица не является средством массовой информации.</p>
    <p class="agreement__text">Используя сайт, Вы соглашаетесь с условиями данного соглашения.</p>
    <p class="agreement__text agreement__text_type_accent">Если Вы не согласны с условиями данного соглашения, не используйте сайт Кубанская кормилица!</p>
    <ul class="agreement__list">
      <li class="agreement__item">
        <h3 class="agreement__subtitle">Предмет соглашения</h3>
        <p class="agreement__text agreement__text_type_accent">Администрация предоставляет пользователю право на размещение на сайте следующей информации:</p>
        <ul class="agreement__sublist">
          <li class="agreement__item">Текстовой информации</li>
          <li class="agreement__item">Ссылок на материалы, размещенные на других сайтах</li>
        </ul>
      </li>
      <li class="agreement__item">
        <h3 class="agreement__subtitle">Права и обязанности сторон</h3>
        <ul class="agreement__sublist">
          <li class="agreement__item">
            <p class="agreement__text_type_accent">Пользователь имеет право:</p>
            <ul class="agreement__sublist">
              <li class="agreement__item">осуществлять поиск информации на сайте</li>
              <li class="agreement__item">получать информацию на сайте</li>
              <li class="agreement__item">использовать информацию сайта в личных некоммерческих целях</li>
            </ul>
          </li>
          <li class="agreement__item">
            <p class="agreement__text_type_accent">Администрация имеет право:</p>
            <ul class="agreement__sublist">
              <li class="agreement__item">по своему усмотрению и необходимости создавать, изменять, отменять правила</li>
              <li class="agreement__item">ограничивать доступ к любой информации на сайте</li>
              <li class="agreement__item">создавать, изменять, удалять информацию</li>
            </ul>
          </li>
          <li class="agreement__item">
            <p class="agreement__text_type_accent">Пользователь обязуется:</p>
            <ul class="agreement__sublist">
              <li class="agreement__item">обеспечить достоверность предоставляемой информации</li>
              <li class="agreement__item">не нарушать работоспособность сайта</li>
              <li class="agreement__item">не использовать скрипты (программы) для автоматизированного сбора информации и/или взаимодействия с Сайтом и его Сервисами</li>
            </ul>
          </li>
          <li class="agreement__item">
            <p class="agreement__text_type_accent">Администрация обязуется:</p>
            <ul class="agreement__sublist">
              <li class="agreement__item">поддерживать работоспособность сайта за исключением случаев, когда это невозможно по независящим от Администрации причинам.</li>
            </ul>
          </li>
        </ul>
      </li>
      <li class="agreement__item">
        <h3 class="agreement__subtitle">Ответственность сторон</h3>
        <ul class="agreement__sublist">
          <li class="agreement__item">администрация не несет никакой ответственности за достоверность информации, скопированной из других источников</li>
          <li class="agreement__item">администрация не несёт ответственность за несовпадение ожидаемых Пользователем и реально полученных услуг</li>
          <li class="agreement__item">администрация не несет никакой ответственности за услуги, предоставляемые третьими лицами</li>
          <li class="agreement__item">в случае возникновения форс-мажорной ситуации (боевые действия, чрезвычайное положение, стихийное бедствие и т. д.) Администрация не гарантирует сохранность информации, размещённой Пользователем, а также бесперебойную работу информационного ресурса</li>
        </ul>
      </li>
      <li class="agreement__item">
        <h3 class="agreement__subtitle">Условия действия Соглашения</h3>
        <p class="agreement__text">Данное Соглашение вступает в силу при любом использовании данного сайта.
          Соглашение перестает действовать при появлении его новой версии. Администрация оставляет за собой право
          в одностороннем порядке изменять данное соглашение по своему усмотрению. Администрация не оповещает
          пользователей об изменении в Соглашении.</p>
      </li>
    </ul>
  </section>
</main>
{% block script %}
{% endblock script %}
{% endblock content %}

kubansite/pages/templates/pages/category.html
{% extends "base.html" %}
{% load static %}
{% block title %}Каталог{% endblock title %}
{% block keywords %}кондитерские изделия, оптом, конфеты, печенье, торты{% endblock keywords %}
{% block description %}На кондитерском производстве Кубанская кормилица вы можете приобрести по оптовым ценам
такие изделия, как конфеты, печенье, пряники, сушки, слойки и батончики{% endblock description %}
{% block content %}
<main class="content">
  <section class="category">
    <div class="category__nav">
      <nav class="breadcrumbs">
        <a href="{% url 'katalog' %}" class="breadcrumbs__link">Каталог</a>
        <span class="breadcrumbs__arrow_active"></span>
        <a href="" class="breadcrumbs__link breadcrumbs__link_active">{{category.title}}</a>
      </nav>
      <form action="" class="filter__form" method="post">{% csrf_token %}
        <div class="filter__input-container">
          {{form.title}}
        </div>
        <!-- <input type="submit" value="Create" /> форма -->
      </form>
    </div>
    <h1 class="category__title">{{category.title}}</h1>
    <ul class="table">
      {%for i in page_obj%}
      <li class="table__item-container">
        <a class="table__link" href="{% url 'product' i.id %}">
          <div class="table__item">
              <img class="table__image" src= {{i.photo.url}} alt={{i.title}}>
              <p class="table__text">{{i.title}}</p>
          </div>
        </a>
      </li>
      {% endfor %}
    </ul>
  {% include 'paginator.html' %}
  </section>
</main>
{% block script %}
  <script defer src="{%static './scripts/category.js' %}"></script>
{% endblock script %}
{% endblock content %}

kubansite/pages/templates/pages/contacts.html
{% extends "base.html" %}
{% load static %}
{% block title %}Сотрудничество{% endblock title %}
{% block keywords %}кондитерские изделия, оптом, конфеты, печенье, торты{% endblock keywords %}
{% block description %}Мы предлагаем вам оставить свои контакты, чтобы наш
менеджер связался с вами, и вы смогли приобрести кондитерские изделия по оптовым ценам
на выгодных условиях{% endblock description %}
{% block content %}
<main class="content">
  <section class="cooperation">
    {% if form.errors %}
      {% for field in form %} <!-- вывод ошибок для каждого поля, если они есть-->
        {% for error in field.errors %}
            {{ error|escape }}
        {% endfor %}
      {% endfor %}
      {% for error in form.non_field_errors %}
          {{ error|escape }}
      {% endfor %}
      {% endif %}
                    {%if flag %}
                      <p class="text cooperation__confirm">Спасибо! Ваша заявка сохранена!</p>
                    {%endif%}

    <h1 class="section-title cooperation__section-title">cотрудничество</h1>
    <p class="text cooperation__subtitle">
      Мы предлагаем качественные кондитерские изделия и долгосрочное взаимовыгодное сотрудничество.
    </p>
    <div class="cooperation__container">
      <p class="text cooperation__description">
        Мы сотрудничаем со всей Россией, Китаем, Грузией, Абхазией, Казахстаном и предлагаем нашим потенциальным
        партнёрам — региональным торговым сетям или крупным оптовым компаниям, ознакомиться с ассортиментом продукции.
      </p>
      <img class="guarantee__image" src="{% static './images/map.webp' %}" alt="круассаны">
    </div>
    <div class="cooperation__info">
      <p class="text cooperation__text">
        По условиям поставок свяжитесь любым удобным для вас способом или отправьте заявку, наш менеджер свяжется
        с вами для уточнения деталей и предложит варианты сотрудничества.
      </p>
      <a href="#cooperation" class="btn btn-light button_type_contact cooperation__button">Отправить заявку</a>
    </div>
  </section>
  <section class="popup" id="cooperation">
    <div class="popup__container">
      <img class="popup__logo" src="{% static './images/logo.svg' %}" alt="">
      <h2 class="popup__title">Станьте нашими партнёрами</h2>
      <p class="popup__subtitle">Оставьте свои контактные данные и мы вам перезвоним</p>
      <form
        name="contact_form"
        method="post"
        class="form popup__form"
        name="card-information"
        novalidate
      >
        {% csrf_token %}
        <div class="">
          <div>
            {{form.first_name}} <!--Имя-->
            <span class="popup__error {{form.first_name.name}}-error"></span>
          </div>
          <div>
            {{form.phone_number}}<!--Номер телефона-->
            <span class="popup__error {{form.phone_number.name}}-error"></span>
          </div>
          <div>
            {{form.e_mail}}<!--Электронная почта-->
            <span class="popup__error {{form.e_mail.name}}-error"></span>
          </div>
          <div>
            {{form.region}}<!--Регион-->
          </div>
          <div class="popup__select-wrapper popup__select_type_chanel">
            <label class="popup__select-label" for="id_sales_channel">Канал продаж</label>
            {{form.sales_channel}}<!--Канал продаж-->
          </div>
          <div class="popup__select-wrapper popup__select-wrapper_type_tax">
            <label class="popup__select-label" for="id_nalog">Налог</label>
            {{form.nalog}}<!--Налог-->
          </div>
          <div>
            {{form.text}}<!--Сообщение-->
          </div>
          <p class="text popup__reminder"> *поля обязательные к заполнению </p>
          <div class="option-template-container">
            <label for="id_rules" class="service-form__label">
              {{ form.rules }}
              <span class="form__pseudo-item form__pseudo-item_type_radio"></span>
              <p class="service-form__label-text">Я принимаю условия <a class="popup__link" target="_blank" href="{% url 'agreement' %}">пользовательского соглашения</a></p>
            </label>
            <span class="popup__error {{form.rules.name}}-error"></span>
          </div>
        </div>
          <button
          class="btn btn-light popup__button"
          type="submit"
          title="Сохранить">
          Отправить
        </button>
      </form>
    </div>
  </section>
</main>
{% endblock content %}
{% block script %}
  <script defer src="{% static 'scripts/cooperation.js' %}"></script>
{% endblock script %}

kubansite/pages/templates/pages/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Кубанская кормилица{% endblock title %}
{% block keywords %}кондитерские изделия, оптом, конфеты, печенье, торты{% endblock keywords %}
{% block description %}На кондитерском производстве Кубанская кормилица вы можете приобрести по оптовым ценам
такие изделия, как конфеты, печенье, пряники, сушки, слойки и батончики{% endblock description %}
{% block css %}
<link rel="stylesheet" href="{% static 'pages/animate.css' %}">
{% endblock css %}
{% block content %}
<main class="content">
  <section class="rent">
    <div class="rent__info">
      <h1 class="rent__section-title">вкус детства на&nbsp;вашем столе</h1>
      <div class="rent__btn-container">
        <a href="{% url 'contacts' %}#cooperation" class="btn btn-light button_type_contact">Связаться с нами</a>
        {% for i in catalog %}
        <a href="{{i.catalog.url}}" download class="btn btn-dark">Скачать каталог</a>
        {% endfor %}
      </div>
    </div>
    <img src="{%static './images/welcome.png'%}" alt="" class="rent__image">
  </section>
  <section class="guide">
    <img class="guide__image wow flip" data-wow-iteration="infinite" data-wow-duration="3s" src="{%static './images/kolos.svg'%}" alt="колосок">
    <p class="text guide__text">«Кубанская кормилица — кондитерское производство, которое знают и любят более 20 лет.
      Мы заботимся о качестве нашей продукции, используем только самые свежие и качественные ингредиенты, делаем все,
      чтобы удовлетворить вкусовые потребности наших клиентов».</p>
  </section>
  <section class="benefit">
    <div class="benefit__text-container">
      <h2 class="benefit__title section-title">наше производство</h2>
      <p class="benefit__text text">Производство оснащено самым современным оборудованием, мы следим за тем, чтобы все процессы
      были выполнены в соответствии со стандартами качества и ГОСТа. Фабрика не использует искусственные красители, консерванты,
      ароматизаторы, поэтому наша продукция всегда свежая и полезная.</p>
    </div>
  </section>
  <section class="choose-home" id="products">
    <h2 class="choose-home__title section-title">продукция</h2>
    <ul class="choose-home__list">
      <li class="choose-home__item">
        <img src="{%static './images/pechsach.png'%}" alt="Печенье сахарное" class="choose-home__image">
        <h3 class="choose-home__item-title">печенье сахарное</h3>
      </li>
      <li class="choose-home__item">
        <img src="{%static './images/pechsdob.png'%}" alt="Печенье сдобное" class="choose-home__image">
        <h3 class="choose-home__item-title">печенье сдобное</h3>
      </li>
      <li class="choose-home__item">
        <img src="{%static './images/krekery.png'%}" alt="Крекеры и галеты" class="choose-home__image">
        <h3 class="choose-home__item-title">крекеры и галеты</h3>
      </li>
      <li class="choose-home__item">
        <img src="{%static './images/pryaniky-syrc.png'%}" alt="Пряники сырцовые" class="choose-home__image">
        <h3 class="choose-home__item-title">пряники сырцовые</h3>
      </li>
      <li class="choose-home__item">
        <img src="{%static './images/pryaniky-pech.png'%}" alt="Пряники печатные" class="choose-home__image">
        <h3 class="choose-home__item-title">пряники печатные</h3>
      </li>
      <li class="choose-home__item">
        <img src="{%static './images/sloyki.png'%}" alt="Слойки/рогалики" class="choose-home__image">
        <h3 class="choose-home__item-title">слойки/рогалики</h3>
      </li>
      <li class="choose-home__item">
        <img src="{%static './images/solomka.png'%}" alt="Соломка" class="choose-home__image">
        <h3 class="choose-home__item-title">соломка</h3>
      </li>
      <li class="choose-home__item">
        <img src="{%static './images/sushki.png'%}" alt="Сухарики/сушки" class="choose-home__image">
        <h3 class="choose-home__item-title">сухарики/сушки</h3>
      </li>
      <li class="choose-home__item">
        <img src="{%static './images/konfety-vaf.png'%}" alt="Конфеты вафельные" class="choose-home__image">
        <h3 class="choose-home__item-title">конфеты вафельные</h3>
      </li>
      <li class="choose-home__item">
        <img src="{%static './images/batonchiki.png'%}" alt="Батончики" class="choose-home__image">
        <h3 class="choose-home__item-title">батончики</h3>
      </li>
    </ul>
    <a href="{%static './catalog/catalog.pdf' %}" download class="btn btn-dark choose-home__button">Скачать полную версию каталога</a>
  </section>
  <section class="guarantee">
    <div class="guarantee__info">
      <h2 class="section-title guarantee__section-title">гарантия качества</h2>
      <p class="text guarantee__text">
        Наши кондитерские и хлебобулочные изделия готовятся с любовью и заботой о качестве.
        Мы всегда стараемся удовлетворить потребности наших клиентов, предлагая разнообразные вкусы и формы.
      </p>
      <a href="{% url 'contacts' %}" class="btn btn-light guarantee__button button_type_contact">Связаться с нами</a>
    </div>
    <img class="guarantee__image" src="{% static './images/croissants.png'%}" alt="круассаны">
  </section>
  <section class="guide">
    <img class="guide__image wow flip" data-wow-iteration="infinite" data-wow-duration="3s" src="{%static './images/kolos.svg'%}" alt="колосок">
    <p class="text guide__text">«Кубанская кормилица — это не только продукция, это любовь к делу и забота о каждом нашем клиенте.
      Мы всегда открыты для общения и готовы обсудить любые вопросы и предложения. Благодарим вас за то, что выбираете нас!»</p>
  </section>
</main>
{% endblock content %}
{% block script %}
  <script src="{% static './scripts/wow.min.js' %}"></script>
  <script>
    new WOW().init();
  </script>
{% endblock script %}

kubansite/pages/templates/pages/katalog.html
{% extends "base.html" %}
{% load static %}
{% block title %}Каталог{% endblock title %}
{% block keywords %}кондитерские изделия, оптом, конфеты, печенье, торты{% endblock keywords %}
{% block description %}На странице представлен каталог, который включается такое категории, как конфеты, печенье, пряники,
сушки, слойки и батончики{% endblock description %}
{% block content %}
<main class="content">
  <section class="catalog">
    <h1 class="category__title">каталог продукции</h1>
    <ul class="table">
      {% for i in page_obj%}
      <li class="table__item-container">
        <a class="table__link" href="{% url 'category' i.slug %}">
          <div class="table__item">
            <img class="table__image" alt="" src="{{i.photo.url}}">
            <p class="table__text">{{i}}</p>
          </div>
        </a>
      </li>
      {% endfor %}
    </ul>
  </section>
</main>
{% include 'paginator.html' %}
{% endblock content %}

kubansite/pages/templates/pages/product.html
{% extends "base.html" %}
{% load static %}
{% block title %}Каталог{% endblock title %}
{% block css %}<link rel="stylesheet" href="{% static 'pages/simple-adaptive-slider.css' %}">{% endblock css %}
{% block keywords %}кондитерские изделия, оптом, конфеты, печенье, торты{% endblock keywords %}
{% block description %}На кондитерском производстве Кубанская кормилица вы можете приобрести по оптовым ценам
такие изделия, как конфеты, печенье, пряники, сушки, слойки и батончики{% endblock description %}
{% block content %}
<main class="content">
  <section class="product">
    <nav class="breadcrumbs">
      <a href="{% url 'katalog' %}" class="breadcrumbs__link">Каталог</a>
      <span class="breadcrumbs__arrow"></span>
      <a href="{%url 'category' product.category.slug %}" class="breadcrumbs__link">{{product.category}}</a>
      <span class="breadcrumbs__arrow_active"></span>
      <a href="" class="breadcrumbs__link breadcrumbs__link_active">{{product.title}}</a>
    </nav>
    <div class="product__container">
      <div class="product__slider-container itcss">
        <button class="slider__control slider__control_prev" href="#" role="button" data-slide="prev"></button>
        <div class="product__slider itcss__wrapper">
          <ul class="product__slider-list itcss__items">
            <li class="product__slider-item itcss__item"><img class="product__image" src={{product.photo.url}}></li>
            {% for i in images %}
            <li class="product__slider-item itcss__item">
              <img class="product__image" src={{i.image.url}}>
            </li>
            {% endfor %}
          </ul>
        </div>
        <button class="slider__control slider__control_next" href="#" role="button" data-slide="next"></button>
      </div>
      <div class="product__info">
        <h1 class="product__title">{{product.title}}</h1>
        <div class="product__description">
          <p class="product__text product__weight">{{product.weight}}</p>
          <p class="product__text">Категория фасовки - {{product.weight_category.title}}</p>
          <p class="product__text product__date">Срок годности - {{product.expiration_date}}</p>
          <!-- <p class="product__text product__package">Упаковка - <a href="" class="product__link">{{product.packaging}}</a></p> -->
          <p class="product__text product__quantity">Количество вложения - {{product.quantity_a}}</p>
        </div>
      </div>
    </div>
  </section>
</main>
{% endblock content %}
{% block script %}
<script defer name="slider" src="{%static './scripts/slider.js' %}"></script>
{% endblock script %}